name             "chef-sensu"
maintainer       "Vegard Hansen"
maintainer_email "vegard.x@gmail.com"
license          "Apache 2.0"
description      "Installs/configures sensu"
version          "1.0.0"
